# Generated by Django 5.2.10 on 2026-01-22 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShopData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ad_group", models.CharField(max_length=255)),
                ("month", models.CharField(max_length=20)),
                ("impressions", models.IntegerField()),
                ("clicks", models.IntegerField()),
                ("ctr", models.FloatField()),
                ("conversions", models.IntegerField()),
                ("conv_rate", models.FloatField()),
                ("cost", models.FloatField()),
                ("cpc", models.FloatField()),
                ("revenue", models.FloatField()),
                ("sale_amount", models.FloatField()),
                ("pandl", models.FloatField()),
            ],
        ),
    ]
